### ISSUE TITLE
sass bug de plugin

### ISSUE THREAD

**Issue by xWiZz** [xWiZz/Virtual-Keyboard#1]
Après avoir fait l'installation de node et gulp, je rencontre un problème lorsque j'essaie de compiler et de watch mon code.
Voici la commande que j'exécute : **gulp**  
Une fois cette commande exécutée, le message suivant apparait : 
`[11:12:32] Using gulpfile ~/Desktop/Dev' 🧮/Virtual Keyboard/gulpfile.js 
[11:12:32] Starting 'default'... 
[11:12:32] 'default' errored after 20 ms  
[11:12:32] Error in plugin 'gulp-compass' 
Message:
    You need to have Ruby and Compass installed and in your system PATH for this task to work.
Details:
    domainEmitter: [object Object]
    domainThrown: false`

Le principal problème est que, lorsque j'installe ruby sur ma machine, beaucoup d'erreurs se produisent et je suis incapable de les résoudres, est-ce qu'il y aurait des variantes ? Un plugin gulp sans passer par ruby ?

**Comment by Herondil** [comment]
En tapant "gulp sass" sur duckduckgo, je trouve ce plug-in : https://www.npmjs.com/package/gulp-sass Est-ce que tu le connais ?

**Comment by xWiZz** [comment]
Non je ne connais pas ce plug-in. Je vais me pencher dessus pour voir ce qu'il propose !

**Comment by xWiZz** [comment]
@Herondil 1000 merci ! J'ai enfin trouvé solution à mon problème de gulp !
